//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechSpecFilter
    {
        public int subCategoryID { get; set; }
        public int attributeID { get; set; }
        public string maxVal { get; set; }
        public string minVal { get; set; }
    
        public virtual tblAttribute tblAttribute { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
