//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleApp.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblUser
    {
        public int userID { get; set; }

        [Required(ErrorMessage = "User name is required.")]
        public string userName { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        public string password { get; set; }

        [NotMapped] // Does not effect with your database
        [Compare("password", ErrorMessage = "Confirm password doesn't match, Type again !")]
        public string confirmPassword { get; set; }
        public string emailAddress { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userAddress { get; set; }
        public string phone { get; set; }
        public string userImage { get; set; }
    }
}
